import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar2 from "@/components/NavBar2";
import Footer from "@/components/Footer";
import NextThemeProvider from "./providers/NextThemeProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme= 'light'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        
       
       <NextThemeProvider>
              <NavBar2></NavBar2>
            
              <main>
                  {children}
              </main>
              <Footer></Footer>

       </NextThemeProvider>


        </body>
    </html>
  );
}
